from __future__ import annotations

import io
import tarfile
from dataclasses import dataclass
from datetime import datetime
from html import escape
import re
from pathlib import Path
from tempfile import TemporaryDirectory

from sqlmodel import select

from backend.backend.config import get_settings
from backend.backend.db import get_session
from backend.backend.llm.mock import MockCodeLLM
from backend.backend.models import Build, Event, Revision
from backend.backend.storage import put_bytes
from .logger import get_logger

logger = get_logger("worker")

STYLE_PRESETS = {
    "minimal": {
        "background": "#020617",
        "foreground": "#e2e8f0",
        "muted": "#94a3b8",
        "accent": "#38bdf8",
        "accent_text": "#020617",
    },
    "cozy": {
        "background": "#fef3c7",
        "foreground": "#422006",
        "muted": "#a16207",
        "accent": "#f97316",
        "accent_text": "#fff7ed",
    },
    "retro": {
        "background": "#064e3b",
        "foreground": "#ecfdf5",
        "muted": "#34d399",
        "accent": "#fbbf24",
        "accent_text": "#0f172a",
    },
}


TITLE_RE = re.compile(r"<h1[^>]*>(?P<title>.+?)</h1>", re.DOTALL)
BODY_RE = re.compile(r"<p[^>]*>(?P<body>.+?)</p>", re.DOTALL)


@dataclass
class PreviewPage:
    slug: str
    title: str
    body: str

    @property
    def route(self) -> str:
        if self.slug in {"", "index"}:
            return "/"
        slug = self.slug
        if slug.endswith("/index"):
            slug = slug[: -len("/index")]
        return "/" + slug if slug else "/"

    @property
    def output_path(self) -> str:
        if self.slug in {"", "index"}:
            return "index.html"
        slug = self.slug
        if slug.endswith("/index"):
            slug = slug[: -len("/index")]
        return f"{slug}/index.html"


def _extract_text(pattern: re.Pattern[str], source: str) -> str | None:
    match = pattern.search(source)
    if not match:
        return None
    text = match.group(1).strip()
    return text


def _collect_preview_pages(tree_files: dict[str, str]) -> list[PreviewPage]:
    pages: list[PreviewPage] = []
    for path, content in tree_files.items():
        if not path.startswith("pages/") or not path.endswith(".tsx"):
            continue
        if path.startswith("pages/api/"):
            continue
        slug = path[len("pages/") : -len(".tsx")]
        title = _extract_text(TITLE_RE, content)
        body = _extract_text(BODY_RE, content)
        if not title and not body:
            continue
        pages.append(
            PreviewPage(
                slug=slug,
                title=title or "Preview",
                body=body or "This page was generated by Vibecoder.",
            )
        )
    # Ensure the homepage is first for nav ordering.
    pages.sort(key=lambda page: (page.slug not in {"", "index"}, page.slug))
    return pages


def _render_preview_page(page: PreviewPage, pages: list[PreviewPage], style: str) -> str:
    theme = STYLE_PRESETS.get(style, STYLE_PRESETS["minimal"])
    nav_links = []
    for candidate in pages:
        href = candidate.route
        label = candidate.title
        nav_links.append((href, label))

    nav_html = "".join(f'<a href="{escape(href)}">{escape(label)}</a>' for href, label in nav_links)

    body_text = escape(page.body).replace("\n", "<br />")
    title_text = escape(page.title)

    cta_target = next((href for href, _ in nav_links if href != "/" and "contact" in href.lower()), None)
    if not cta_target:
        cta_target = nav_links[0][0] if nav_links else "/"

    return f"""<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>{title_text}</title>
    <style>
      * {{ box-sizing: border-box; }}
      body {{
        margin: 0;
        font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif;
        background: {theme['background']};
        color: {theme['foreground']};
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: stretch;
      }}
      header {{
        padding: 2rem 1.5rem 1rem;
        text-align: center;
      }}
      header h1 {{
        font-size: 2.25rem;
        margin: 0;
        letter-spacing: -0.02em;
      }}
      nav {{
        margin-top: 1.5rem;
        display: flex;
        flex-wrap: wrap;
        gap: 0.75rem;
        justify-content: center;
      }}
      nav a {{
        color: {theme['accent']};
        text-decoration: none;
        font-weight: 600;
        padding: 0.5rem 1rem;
        border-radius: 999px;
        background: rgba(255, 255, 255, 0.08);
        border: 1px solid rgba(255, 255, 255, 0.12);
      }}
      nav a:hover {{
        background: {theme['accent']};
        color: {theme['accent_text']};
      }}
      main {{
        flex: 1;
        width: min(720px, 92vw);
        margin: 0 auto;
        padding: 0 1.5rem 3rem;
        text-align: center;
      }}
      main h2 {{
        font-size: 2rem;
        margin-top: 0;
      }}
      main p {{
        line-height: 1.7;
        margin-top: 1.25rem;
        font-size: 1.1rem;
        color: {theme['muted']};
      }}
      .cta {{
        display: inline-flex;
        align-items: center;
        justify-content: center;
        margin-top: 2rem;
        padding: 0.75rem 1.5rem;
        border-radius: 999px;
        background: {theme['accent']};
        color: {theme['accent_text']};
        text-decoration: none;
        font-weight: 600;
        box-shadow: 0 15px 35px rgba(0,0,0,0.2);
      }}
      .cta:hover {{
        opacity: 0.9;
      }}
      footer {{
        padding: 1.5rem;
        text-align: center;
        font-size: 0.85rem;
        color: {theme['muted']};
      }}
    </style>
  </head>
  <body>
    <header>
      <h1>{title_text}</h1>
      <nav>
        {nav_html}
      </nav>
    </header>
    <main>
      <h2>{title_text}</h2>
      <p>{body_text}</p>
      <a class=\"cta\" href=\"{escape(cta_target)}\">Let's talk</a>
    </main>
    <footer>Generated by Vibecoder</footer>
  </body>
</html>"""


def _generate_preview_files(tree_files: dict[str, str], style: str) -> dict[str, str]:
    pages = _collect_preview_pages(tree_files)
    if not pages:
        fallback = PreviewPage(slug="index", title="Preview", body="Preview content unavailable.")
        pages = [fallback]
    preview: dict[str, str] = {}
    for page in pages:
        html = _render_preview_page(page, pages, style)
        preview[page.output_path] = html
    return preview


def _write_tree(base: Path, files: dict[str, str]) -> None:
    for rel_path, content in files.items():
        target = base / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def _tar_directory(path: Path) -> bytes:
    buffer = io.BytesIO()
    with tarfile.open(mode="w:gz", fileobj=buffer) as tar:
        tar.add(path, arcname=".")
    buffer.seek(0)
    return buffer.read()


def run_pipeline(payload: dict[str, str]) -> None:
    revision_id = payload["revision_id"]
    prompt = payload.get("prompt", "")
    vibe = payload.get("vibe")

    settings = get_settings()
    llm = MockCodeLLM()
    logger.info("pipeline.start", revision_id=revision_id, step="plan")
    plan = llm.plan(prompt, vibe)
    tree = llm.scaffold(plan)

    with TemporaryDirectory() as tmpdir:
        workdir = Path(tmpdir)
        _write_tree(workdir, tree.files)

        artifact_bytes = _tar_directory(workdir)
        artifact_path = f"artifacts/{revision_id}.tar.gz"
        put_bytes(artifact_path, artifact_bytes, content_type="application/gzip")

        preview_files = _generate_preview_files(tree.files, plan.style)
        for rel_path, html in preview_files.items():
            preview_path = f"previews/{revision_id}/{rel_path}"
            put_bytes(preview_path, html.encode("utf-8"), content_type="text/html; charset=utf-8")

        diff_text = "Generated files:\n" + "\n".join(sorted(tree.files.keys()))
        log_text = "Plan successful\nScaffolded files\nBuild skipped (mock)\nVerify passed"
        logs_path = f"logs/{revision_id}.log"
        put_bytes(logs_path, log_text.encode(), content_type="text/plain")

    preview_url = f"http://{revision_id}.{settings.preview_base_host}:8080/"

    with get_session() as session:
        revision = session.get(Revision, revision_id)
        if not revision:
            logger.error("revision missing", revision_id=revision_id)
            return
        revision.status = "succeeded"
        revision.artifact_path = artifact_path
        revision.logs_path = logs_path
        session.add(revision)

        build = session.exec(select(Build).where(Build.revision_id == revision_id)).first()
        finished_at = datetime.utcnow()
        if build is None:
            build = Build(revision_id=revision_id, status="succeeded", preview_url=preview_url, finished_at=finished_at)
        else:
            build.status = "succeeded"
            build.finished_at = finished_at
            build.preview_url = preview_url
        session.add(build)

        event = Event(project_id=revision.project_id, revision_id=revision.id, kind="diff", payload_json=diff_text)
        session.add(event)
        session.commit()

    logger.info("pipeline.complete", revision_id=revision_id, step="done", preview_url=preview_url)
